// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkfjinzhlbdqduosyjbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrZmppbnpobGJkcWR1b3N5amJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MzM1MTYsImV4cCI6MjA3MjEwOTUxNn0.OrhCMEy3JzezvguY0NOgPWHwkzByOMM9T53fvEgwtjc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});